Repository Turbo87/ogn-web-gateway, pull requests merged in 2019-01, with the labels that each got.

#104 Add `--host` and `--port` CLI options
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: enhancement

#111 Update Rust to v1.32.0
  .travis.yml
  src/api/status.rs
  src/geo.rs
  src/ogn/aprs.rs
Labels: internal

#112 Update locked dependencies
  Cargo.lock
Labels: dependencies

#113 CI: Improve config
  .travis.yml
Labels: internal

#114 Add `clippy` linting
  .travis.yml
  src/api/records.rs
  src/gateway.rs
  src/main.rs
  src/ogn/aprs.rs
  src/ogn/time.rs
  src/redis/positions.rs
Labels: internal

#115 Add CORS headers to `/api` endpoints
  src/app.rs
Labels: enhancement

#116 Speed up CI
  .travis.yml
Labels: internal

#117 Add default values to CLI arguments
  src/main.rs
Labels: enhancement
